/*******************************************************************************
* DISCLAIMER
* This software is supplied by Renesas Electronics Corporation and is only
* intended for use with Renesas products. No other uses are authorized. This
* software is owned by Renesas Electronics Corporation and is protected under
* all applicable laws, including copyright laws.
* THIS SOFTWARE IS PROVIDED "AS IS" AND RENESAS MAKES NO WARRANTIES REGARDING
* THIS SOFTWARE, WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING BUT NOT
* LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE
* AND NON-INFRINGEMENT. ALL SUCH WARRANTIES ARE EXPRESSLY DISCLAIMED.
* TO THE MAXIMUM EXTENT PERMITTED NOT PROHIBITED BY LAW, NEITHER RENESAS
* ELECTRONICS CORPORATION NOR ANY OF ITS AFFILIATED COMPANIES SHALL BE LIABLE
* FOR ANY DIRECT, INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES FOR
* ANY REASON RELATED TO THIS SOFTWARE, EVEN IF RENESAS OR ITS AFFILIATES HAVE
* BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
* Renesas reserves the right, without notice, to make changes to this software
* and to discontinue the availability of this software. By using this software,
* you agree to the additional terms and conditions found by accessing the
* following link:
* http://www.renesas.com/disclaimer
* Copyright (C) 2018 Renesas Electronics Corporation. All rights reserved.
*******************************************************************************/ 
#ifndef PMG_IOBITMASK_H
#define PMG_IOBITMASK_H


/* ==== Mask values for IO registers ==== */

#define PMG_RRAMKP_RRAMKP0                                                     (0x01u)
#define PMG_RRAMKP_RRAMKP0_SHIFT                                               (0u)
#define PMG_RRAMKP_RRAMKP1                                                     (0x02u)
#define PMG_RRAMKP_RRAMKP1_SHIFT                                               (1u)
#define PMG_RRAMKP_RRAMKP2                                                     (0x04u)
#define PMG_RRAMKP_RRAMKP2_SHIFT                                               (2u)
#define PMG_RRAMKP_RRAMKP3                                                     (0x08u)
#define PMG_RRAMKP_RRAMKP3_SHIFT                                               (3u)
#define PMG_RRAMKP_CKS                                                         (0x70u)
#define PMG_RRAMKP_CKS_SHIFT                                                   (4u)
#define PMG_DSCTR_RAMBOOT                                                      (0x40u)
#define PMG_DSCTR_RAMBOOT_SHIFT                                                (6u)
#define PMG_DSCTR_EBUSKEEPE                                                    (0x80u)
#define PMG_DSCTR_EBUSKEEPE_SHIFT                                              (7u)
#define PMG_DSSSR_dstbcl0                                                      (0x0001u)
#define PMG_DSSSR_dstbcl0_SHIFT                                                (0u)
#define PMG_DSSSR_dstbcl1                                                      (0x0002u)
#define PMG_DSSSR_dstbcl1_SHIFT                                                (1u)
#define PMG_DSSSR_dstbcl2                                                      (0x0004u)
#define PMG_DSSSR_dstbcl2_SHIFT                                                (2u)
#define PMG_DSSSR_dstbcl3                                                      (0x0008u)
#define PMG_DSSSR_dstbcl3_SHIFT                                                (3u)
#define PMG_DSSSR_dstbcl4                                                      (0x0010u)
#define PMG_DSSSR_dstbcl4_SHIFT                                                (4u)
#define PMG_DSSSR_dstbcl5                                                      (0x0020u)
#define PMG_DSSSR_dstbcl5_SHIFT                                                (5u)
#define PMG_DSSSR_RTCAR0                                                       (0x0040u)
#define PMG_DSSSR_RTCAR0_SHIFT                                                 (6u)
#define PMG_DSSSR_RTCAR1                                                       (0x0080u)
#define PMG_DSSSR_RTCAR1_SHIFT                                                 (7u)
#define PMG_DSSSR_NMI                                                          (0x0100u)
#define PMG_DSSSR_NMI_SHIFT                                                    (8u)
#define PMG_DSSSR_dstbcl6                                                      (0x0200u)
#define PMG_DSSSR_dstbcl6_SHIFT                                                (9u)
#define PMG_DSSSR_dstbcl7                                                      (0x0400u)
#define PMG_DSSSR_dstbcl7_SHIFT                                                (10u)
#define PMG_DSSSR_dstbcl8                                                      (0x0800u)
#define PMG_DSSSR_dstbcl8_SHIFT                                                (11u)
#define PMG_DSSSR_dstbcl9                                                      (0x1000u)
#define PMG_DSSSR_dstbcl9_SHIFT                                                (12u)
#define PMG_DSSSR_dstbcl10                                                     (0x2000u)
#define PMG_DSSSR_dstbcl10_SHIFT                                               (13u)
#define PMG_DSSSR_dstbcl11                                                     (0x4000u)
#define PMG_DSSSR_dstbcl11_SHIFT                                               (14u)
#define PMG_DSESR_dstbcl0E                                                     (0x0001u)
#define PMG_DSESR_dstbcl0E_SHIFT                                               (0u)
#define PMG_DSESR_dstbcl1E                                                     (0x0002u)
#define PMG_DSESR_dstbcl1E_SHIFT                                               (1u)
#define PMG_DSESR_dstbcl2E                                                     (0x0004u)
#define PMG_DSESR_dstbcl2E_SHIFT                                               (2u)
#define PMG_DSESR_dstbcl3E                                                     (0x0008u)
#define PMG_DSESR_dstbcl3E_SHIFT                                               (3u)
#define PMG_DSESR_dstbcl4E                                                     (0x0010u)
#define PMG_DSESR_dstbcl4E_SHIFT                                               (4u)
#define PMG_DSESR_dstbcl5E                                                     (0x0020u)
#define PMG_DSESR_dstbcl5E_SHIFT                                               (5u)
#define PMG_DSESR_NMIE                                                         (0x0100u)
#define PMG_DSESR_NMIE_SHIFT                                                   (8u)
#define PMG_DSESR_dstbcl6E                                                     (0x0200u)
#define PMG_DSESR_dstbcl6E_SHIFT                                               (9u)
#define PMG_DSESR_dstbcl7E                                                     (0x0400u)
#define PMG_DSESR_dstbcl7E_SHIFT                                               (10u)
#define PMG_DSESR_dstbcl8E                                                     (0x0800u)
#define PMG_DSESR_dstbcl8E_SHIFT                                               (11u)
#define PMG_DSESR_dstbcl9E                                                     (0x1000u)
#define PMG_DSESR_dstbcl9E_SHIFT                                               (12u)
#define PMG_DSESR_dstbcl10E                                                    (0x2000u)
#define PMG_DSESR_dstbcl10E_SHIFT                                              (13u)
#define PMG_DSESR_dstbcl11E                                                    (0x4000u)
#define PMG_DSESR_dstbcl11E_SHIFT                                              (14u)
#define PMG_DSFR_dstbcl0F                                                      (0x0001u)
#define PMG_DSFR_dstbcl0F_SHIFT                                                (0u)
#define PMG_DSFR_dstbcl1F                                                      (0x0002u)
#define PMG_DSFR_dstbcl1F_SHIFT                                                (1u)
#define PMG_DSFR_dstbcl2F                                                      (0x0004u)
#define PMG_DSFR_dstbcl2F_SHIFT                                                (2u)
#define PMG_DSFR_dstbcl3F                                                      (0x0008u)
#define PMG_DSFR_dstbcl3F_SHIFT                                                (3u)
#define PMG_DSFR_dstbcl4F                                                      (0x0010u)
#define PMG_DSFR_dstbcl4F_SHIFT                                                (4u)
#define PMG_DSFR_dstbcl5F                                                      (0x0020u)
#define PMG_DSFR_dstbcl5F_SHIFT                                                (5u)
#define PMG_DSFR_RTCAR0F                                                       (0x0040u)
#define PMG_DSFR_RTCAR0F_SHIFT                                                 (6u)
#define PMG_DSFR_RTCAR1F                                                       (0x0080u)
#define PMG_DSFR_RTCAR1F_SHIFT                                                 (7u)
#define PMG_DSFR_NMIF                                                          (0x0100u)
#define PMG_DSFR_NMIF_SHIFT                                                    (8u)
#define PMG_DSFR_dstbcl6F                                                      (0x0200u)
#define PMG_DSFR_dstbcl6F_SHIFT                                                (9u)
#define PMG_DSFR_dstbcl7F                                                      (0x0400u)
#define PMG_DSFR_dstbcl7F_SHIFT                                                (10u)
#define PMG_DSFR_dstbcl8F                                                      (0x0800u)
#define PMG_DSFR_dstbcl8F_SHIFT                                                (11u)
#define PMG_DSFR_dstbcl9F                                                      (0x1000u)
#define PMG_DSFR_dstbcl9F_SHIFT                                                (12u)
#define PMG_DSFR_dstbcl10F                                                     (0x2000u)
#define PMG_DSFR_dstbcl10F_SHIFT                                               (13u)
#define PMG_DSFR_dstbcl11F                                                     (0x4000u)
#define PMG_DSFR_dstbcl11F_SHIFT                                               (14u)
#define PMG_DSFR_IOKEEP                                                        (0x8000u)
#define PMG_DSFR_IOKEEP_SHIFT                                                  (15u)
#define PMG_DSCNT_DSCNT                                                        (0x00FFu)
#define PMG_DSCNT_DSCNT_SHIFT                                                  (0u)
#define PMG_XTALCTR_GAIN0                                                      (0x01u)
#define PMG_XTALCTR_GAIN0_SHIFT                                                (0u)
#define PMG_XTALCTR_GAIN1                                                      (0x02u)
#define PMG_XTALCTR_GAIN1_SHIFT                                                (1u)
#define PMG_USBDSSSR_USBDSCE0                                                  (0x01u)
#define PMG_USBDSSSR_USBDSCE0_SHIFT                                            (0u)
#define PMG_USBDSSSR_USBDSCE1                                                  (0x02u)
#define PMG_USBDSSSR_USBDSCE1_SHIFT                                            (1u)
#define PMG_USBDSSSR_USBDSCE2                                                  (0x04u)
#define PMG_USBDSSSR_USBDSCE2_SHIFT                                            (2u)
#define PMG_USBDSSSR_USBDSCE3                                                  (0x08u)
#define PMG_USBDSSSR_USBDSCE3_SHIFT                                            (3u)
#define PMG_USBDSFR_USBDSF0                                                    (0x01u)
#define PMG_USBDSFR_USBDSF0_SHIFT                                              (0u)
#define PMG_USBDSFR_USBDSF1                                                    (0x02u)
#define PMG_USBDSFR_USBDSF1_SHIFT                                              (1u)
#define PMG_USBDSFR_USBDSF2                                                    (0x04u)
#define PMG_USBDSFR_USBDSF2_SHIFT                                              (2u)
#define PMG_USBDSFR_USBDSF3                                                    (0x08u)
#define PMG_USBDSFR_USBDSF3_SHIFT                                              (3u)
#define PMG_ECCRAM_ECCEN0                                                      (0x0001u)
#define PMG_ECCRAM_ECCEN0_SHIFT                                                (0u)
#define PMG_ECCRAM_ECCEN1                                                      (0x0002u)
#define PMG_ECCRAM_ECCEN1_SHIFT                                                (1u)
#define PMG_ECCRAM_ECCEN2                                                      (0x0004u)
#define PMG_ECCRAM_ECCEN2_SHIFT                                                (2u)
#define PMG_ECCERRCTL_EC7TERVE                                                 (0x0001u)
#define PMG_ECCERRCTL_EC7TERVE_SHIFT                                           (0u)
#define PMG_RTCXTALSEL_RTC0XT                                                  (0x0001u)
#define PMG_RTCXTALSEL_RTC0XT_SHIFT                                            (0u)
#define PMG_RTCXTALSEL_RTC1XT                                                  (0x0002u)
#define PMG_RTCXTALSEL_RTC1XT_SHIFT                                            (1u)

#endif
