/*******************************************************************************
* DISCLAIMER
* This software is supplied by Renesas Electronics Corporation and is only
* intended for use with Renesas products. No other uses are authorized. This
* software is owned by Renesas Electronics Corporation and is protected under
* all applicable laws, including copyright laws.
* THIS SOFTWARE IS PROVIDED "AS IS" AND RENESAS MAKES NO WARRANTIES REGARDING
* THIS SOFTWARE, WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING BUT NOT
* LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE
* AND NON-INFRINGEMENT. ALL SUCH WARRANTIES ARE EXPRESSLY DISCLAIMED.
* TO THE MAXIMUM EXTENT PERMITTED NOT PROHIBITED BY LAW, NEITHER RENESAS
* ELECTRONICS CORPORATION NOR ANY OF ITS AFFILIATED COMPANIES SHALL BE LIABLE
* FOR ANY DIRECT, INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES FOR
* ANY REASON RELATED TO THIS SOFTWARE, EVEN IF RENESAS OR ITS AFFILIATES HAVE
* BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
* Renesas reserves the right, without notice, to make changes to this software
* and to discontinue the availability of this software. By using this software,
* you agree to the additional terms and conditions found by accessing the
* following link:
* http://www.renesas.com/disclaimer
* Copyright (C) 2018 Renesas Electronics Corporation. All rights reserved.
*******************************************************************************/ 
#ifndef MTU_IOBITMASK_H
#define MTU_IOBITMASK_H


/* ==== Mask values for IO registers ==== */

#define MTU_TOERA_OE3B                                                         (0x01u)
#define MTU_TOERA_OE3B_SHIFT                                                   (0u)
#define MTU_TOERA_OE4A                                                         (0x02u)
#define MTU_TOERA_OE4A_SHIFT                                                   (1u)
#define MTU_TOERA_OE4B                                                         (0x04u)
#define MTU_TOERA_OE4B_SHIFT                                                   (2u)
#define MTU_TOERA_OE3D                                                         (0x08u)
#define MTU_TOERA_OE3D_SHIFT                                                   (3u)
#define MTU_TOERA_OE4C                                                         (0x10u)
#define MTU_TOERA_OE4C_SHIFT                                                   (4u)
#define MTU_TOERA_OE4D                                                         (0x20u)
#define MTU_TOERA_OE4D_SHIFT                                                   (5u)
#define MTU_TGCRA_UF                                                           (0x01u)
#define MTU_TGCRA_UF_SHIFT                                                     (0u)
#define MTU_TGCRA_VF                                                           (0x02u)
#define MTU_TGCRA_VF_SHIFT                                                     (1u)
#define MTU_TGCRA_WF                                                           (0x04u)
#define MTU_TGCRA_WF_SHIFT                                                     (2u)
#define MTU_TGCRA_FB                                                           (0x08u)
#define MTU_TGCRA_FB_SHIFT                                                     (3u)
#define MTU_TGCRA_P                                                            (0x10u)
#define MTU_TGCRA_P_SHIFT                                                      (4u)
#define MTU_TGCRA_N                                                            (0x20u)
#define MTU_TGCRA_N_SHIFT                                                      (5u)
#define MTU_TGCRA_BDC                                                          (0x40u)
#define MTU_TGCRA_BDC_SHIFT                                                    (6u)
#define MTU_TOCR1A_OLSP                                                        (0x01u)
#define MTU_TOCR1A_OLSP_SHIFT                                                  (0u)
#define MTU_TOCR1A_OLSN                                                        (0x02u)
#define MTU_TOCR1A_OLSN_SHIFT                                                  (1u)
#define MTU_TOCR1A_TOCS                                                        (0x04u)
#define MTU_TOCR1A_TOCS_SHIFT                                                  (2u)
#define MTU_TOCR1A_TOCL                                                        (0x08u)
#define MTU_TOCR1A_TOCL_SHIFT                                                  (3u)
#define MTU_TOCR1A_PSYE                                                        (0x40u)
#define MTU_TOCR1A_PSYE_SHIFT                                                  (6u)
#define MTU_TOCR2A_OLS1P                                                       (0x01u)
#define MTU_TOCR2A_OLS1P_SHIFT                                                 (0u)
#define MTU_TOCR2A_OLS1N                                                       (0x02u)
#define MTU_TOCR2A_OLS1N_SHIFT                                                 (1u)
#define MTU_TOCR2A_OLS2P                                                       (0x04u)
#define MTU_TOCR2A_OLS2P_SHIFT                                                 (2u)
#define MTU_TOCR2A_OLS2N                                                       (0x08u)
#define MTU_TOCR2A_OLS2N_SHIFT                                                 (3u)
#define MTU_TOCR2A_OLS3P                                                       (0x10u)
#define MTU_TOCR2A_OLS3P_SHIFT                                                 (4u)
#define MTU_TOCR2A_OLS3N                                                       (0x20u)
#define MTU_TOCR2A_OLS3N_SHIFT                                                 (5u)
#define MTU_TOCR2A_BF                                                          (0xC0u)
#define MTU_TOCR2A_BF_SHIFT                                                    (6u)
#define MTU_TCDRA_TCDRA                                                        (0xFFFFu)
#define MTU_TCDRA_TCDRA_SHIFT                                                  (0u)
#define MTU_TDDRA_TDDRA                                                        (0xFFFFu)
#define MTU_TDDRA_TDDRA_SHIFT                                                  (0u)
#define MTU_TCNTSA_TCNTSA                                                      (0xFFFFu)
#define MTU_TCNTSA_TCNTSA_SHIFT                                                (0u)
#define MTU_TCBRA_TCBRA                                                        (0xFFFFu)
#define MTU_TCBRA_TCBRA_SHIFT                                                  (0u)
#define MTU_TITCR1A_T4VCOR                                                     (0x07u)
#define MTU_TITCR1A_T4VCOR_SHIFT                                               (0u)
#define MTU_TITCR1A_T4VEN                                                      (0x08u)
#define MTU_TITCR1A_T4VEN_SHIFT                                                (3u)
#define MTU_TITCR1A_T3ACOR                                                     (0x70u)
#define MTU_TITCR1A_T3ACOR_SHIFT                                               (4u)
#define MTU_TITCR1A_T3AEN                                                      (0x80u)
#define MTU_TITCR1A_T3AEN_SHIFT                                                (7u)
#define MTU_TITCNT1A_T4VCNT                                                    (0x07u)
#define MTU_TITCNT1A_T4VCNT_SHIFT                                              (0u)
#define MTU_TITCNT1A_T3ACNT                                                    (0x70u)
#define MTU_TITCNT1A_T3ACNT_SHIFT                                              (4u)
#define MTU_TBTERA_BTE                                                         (0x03u)
#define MTU_TBTERA_BTE_SHIFT                                                   (0u)
#define MTU_TDERA_TDER                                                         (0x01u)
#define MTU_TDERA_TDER_SHIFT                                                   (0u)
#define MTU_TOLBRA_OLS1P                                                       (0x01u)
#define MTU_TOLBRA_OLS1P_SHIFT                                                 (0u)
#define MTU_TOLBRA_OLS1N                                                       (0x02u)
#define MTU_TOLBRA_OLS1N_SHIFT                                                 (1u)
#define MTU_TOLBRA_OLS2P                                                       (0x04u)
#define MTU_TOLBRA_OLS2P_SHIFT                                                 (2u)
#define MTU_TOLBRA_OLS2N                                                       (0x08u)
#define MTU_TOLBRA_OLS2N_SHIFT                                                 (3u)
#define MTU_TOLBRA_OLS3P                                                       (0x10u)
#define MTU_TOLBRA_OLS3P_SHIFT                                                 (4u)
#define MTU_TOLBRA_OLS3N                                                       (0x20u)
#define MTU_TOLBRA_OLS3N_SHIFT                                                 (5u)
#define MTU_TITMRA_TITM                                                        (0x01u)
#define MTU_TITMRA_TITM_SHIFT                                                  (0u)
#define MTU_TITCR2A_TRG4COR                                                    (0x07u)
#define MTU_TITCR2A_TRG4COR_SHIFT                                              (0u)
#define MTU_TITCNT2A_TRG4CNT                                                   (0x07u)
#define MTU_TITCNT2A_TRG4CNT_SHIFT                                             (0u)
#define MTU_TWCRA_WRE                                                          (0x01u)
#define MTU_TWCRA_WRE_SHIFT                                                    (0u)
#define MTU_TWCRA_SCC                                                          (0x02u)
#define MTU_TWCRA_SCC_SHIFT                                                    (1u)
#define MTU_TWCRA_CCE                                                          (0x80u)
#define MTU_TWCRA_CCE_SHIFT                                                    (7u)
#define MTU_TMDR2A_DRS                                                         (0x01u)
#define MTU_TMDR2A_DRS_SHIFT                                                   (0u)
#define MTU_TSTRA_CST0                                                         (0x01u)
#define MTU_TSTRA_CST0_SHIFT                                                   (0u)
#define MTU_TSTRA_CST1                                                         (0x02u)
#define MTU_TSTRA_CST1_SHIFT                                                   (1u)
#define MTU_TSTRA_CST2                                                         (0x04u)
#define MTU_TSTRA_CST2_SHIFT                                                   (2u)
#define MTU_TSTRA_CST8                                                         (0x08u)
#define MTU_TSTRA_CST8_SHIFT                                                   (3u)
#define MTU_TSTRA_CST3                                                         (0x40u)
#define MTU_TSTRA_CST3_SHIFT                                                   (6u)
#define MTU_TSTRA_CST4                                                         (0x80u)
#define MTU_TSTRA_CST4_SHIFT                                                   (7u)
#define MTU_TSYRA_SYNC0                                                        (0x01u)
#define MTU_TSYRA_SYNC0_SHIFT                                                  (0u)
#define MTU_TSYRA_SYNC1                                                        (0x02u)
#define MTU_TSYRA_SYNC1_SHIFT                                                  (1u)
#define MTU_TSYRA_SYNC2                                                        (0x04u)
#define MTU_TSYRA_SYNC2_SHIFT                                                  (2u)
#define MTU_TSYRA_SYNC3                                                        (0x40u)
#define MTU_TSYRA_SYNC3_SHIFT                                                  (6u)
#define MTU_TSYRA_SYNC4                                                        (0x80u)
#define MTU_TSYRA_SYNC4_SHIFT                                                  (7u)
#define MTU_TCSYSTR_SCH7                                                       (0x01u)
#define MTU_TCSYSTR_SCH7_SHIFT                                                 (0u)
#define MTU_TCSYSTR_SCH6                                                       (0x02u)
#define MTU_TCSYSTR_SCH6_SHIFT                                                 (1u)
#define MTU_TCSYSTR_SCH4                                                       (0x08u)
#define MTU_TCSYSTR_SCH4_SHIFT                                                 (3u)
#define MTU_TCSYSTR_SCH3                                                       (0x10u)
#define MTU_TCSYSTR_SCH3_SHIFT                                                 (4u)
#define MTU_TCSYSTR_SCH2                                                       (0x20u)
#define MTU_TCSYSTR_SCH2_SHIFT                                                 (5u)
#define MTU_TCSYSTR_SCH1                                                       (0x40u)
#define MTU_TCSYSTR_SCH1_SHIFT                                                 (6u)
#define MTU_TCSYSTR_SCH0                                                       (0x80u)
#define MTU_TCSYSTR_SCH0_SHIFT                                                 (7u)
#define MTU_TRWERA_RWE                                                         (0x01u)
#define MTU_TRWERA_RWE_SHIFT                                                   (0u)
#define MTU_TOERB_OE6B                                                         (0x01u)
#define MTU_TOERB_OE6B_SHIFT                                                   (0u)
#define MTU_TOERB_OE7A                                                         (0x02u)
#define MTU_TOERB_OE7A_SHIFT                                                   (1u)
#define MTU_TOERB_OE7B                                                         (0x04u)
#define MTU_TOERB_OE7B_SHIFT                                                   (2u)
#define MTU_TOERB_OE6D                                                         (0x08u)
#define MTU_TOERB_OE6D_SHIFT                                                   (3u)
#define MTU_TOERB_OE7C                                                         (0x10u)
#define MTU_TOERB_OE7C_SHIFT                                                   (4u)
#define MTU_TOERB_OE7D                                                         (0x20u)
#define MTU_TOERB_OE7D_SHIFT                                                   (5u)
#define MTU_TOCR1B_OLSP                                                        (0x01u)
#define MTU_TOCR1B_OLSP_SHIFT                                                  (0u)
#define MTU_TOCR1B_OLSN                                                        (0x02u)
#define MTU_TOCR1B_OLSN_SHIFT                                                  (1u)
#define MTU_TOCR1B_TOCS                                                        (0x04u)
#define MTU_TOCR1B_TOCS_SHIFT                                                  (2u)
#define MTU_TOCR1B_TOCL                                                        (0x08u)
#define MTU_TOCR1B_TOCL_SHIFT                                                  (3u)
#define MTU_TOCR1B_PSYE                                                        (0x40u)
#define MTU_TOCR1B_PSYE_SHIFT                                                  (6u)
#define MTU_TOCR2B_OLS1P                                                       (0x01u)
#define MTU_TOCR2B_OLS1P_SHIFT                                                 (0u)
#define MTU_TOCR2B_OLS1N                                                       (0x02u)
#define MTU_TOCR2B_OLS1N_SHIFT                                                 (1u)
#define MTU_TOCR2B_OLS2P                                                       (0x04u)
#define MTU_TOCR2B_OLS2P_SHIFT                                                 (2u)
#define MTU_TOCR2B_OLS2N                                                       (0x08u)
#define MTU_TOCR2B_OLS2N_SHIFT                                                 (3u)
#define MTU_TOCR2B_OLS3P                                                       (0x10u)
#define MTU_TOCR2B_OLS3P_SHIFT                                                 (4u)
#define MTU_TOCR2B_OLS3N                                                       (0x20u)
#define MTU_TOCR2B_OLS3N_SHIFT                                                 (5u)
#define MTU_TOCR2B_BF                                                          (0xC0u)
#define MTU_TOCR2B_BF_SHIFT                                                    (6u)
#define MTU_TCDRB_TCDRB                                                        (0xFFFFu)
#define MTU_TCDRB_TCDRB_SHIFT                                                  (0u)
#define MTU_TDDRB_TDDRB                                                        (0xFFFFu)
#define MTU_TDDRB_TDDRB_SHIFT                                                  (0u)
#define MTU_TCNTSB_TCNTSB                                                      (0xFFFFu)
#define MTU_TCNTSB_TCNTSB_SHIFT                                                (0u)
#define MTU_TCBRB_TCBRB                                                        (0xFFFFu)
#define MTU_TCBRB_TCBRB_SHIFT                                                  (0u)
#define MTU_TITCR1B_T7VCOR                                                     (0x07u)
#define MTU_TITCR1B_T7VCOR_SHIFT                                               (0u)
#define MTU_TITCR1B_T7VEN                                                      (0x08u)
#define MTU_TITCR1B_T7VEN_SHIFT                                                (3u)
#define MTU_TITCR1B_T6ACOR                                                     (0x70u)
#define MTU_TITCR1B_T6ACOR_SHIFT                                               (4u)
#define MTU_TITCR1B_T6AEN                                                      (0x80u)
#define MTU_TITCR1B_T6AEN_SHIFT                                                (7u)
#define MTU_TITCNT1B_T7VCNT                                                    (0x07u)
#define MTU_TITCNT1B_T7VCNT_SHIFT                                              (0u)
#define MTU_TITCNT1B_T6ACNT                                                    (0x70u)
#define MTU_TITCNT1B_T6ACNT_SHIFT                                              (4u)
#define MTU_TBTERB_BTE                                                         (0x03u)
#define MTU_TBTERB_BTE_SHIFT                                                   (0u)
#define MTU_TDERB_TDER                                                         (0x01u)
#define MTU_TDERB_TDER_SHIFT                                                   (0u)
#define MTU_TOLBRB_OLS1P                                                       (0x01u)
#define MTU_TOLBRB_OLS1P_SHIFT                                                 (0u)
#define MTU_TOLBRB_OLS1N                                                       (0x02u)
#define MTU_TOLBRB_OLS1N_SHIFT                                                 (1u)
#define MTU_TOLBRB_OLS2P                                                       (0x04u)
#define MTU_TOLBRB_OLS2P_SHIFT                                                 (2u)
#define MTU_TOLBRB_OLS2N                                                       (0x08u)
#define MTU_TOLBRB_OLS2N_SHIFT                                                 (3u)
#define MTU_TOLBRB_OLS3P                                                       (0x10u)
#define MTU_TOLBRB_OLS3P_SHIFT                                                 (4u)
#define MTU_TOLBRB_OLS3N                                                       (0x20u)
#define MTU_TOLBRB_OLS3N_SHIFT                                                 (5u)
#define MTU_TITMRB_TITM                                                        (0x01u)
#define MTU_TITMRB_TITM_SHIFT                                                  (0u)
#define MTU_TITCR2B_TRG7COR                                                    (0x07u)
#define MTU_TITCR2B_TRG7COR_SHIFT                                              (0u)
#define MTU_TITCNT2B_TRG7CNT                                                   (0x07u)
#define MTU_TITCNT2B_TRG7CNT_SHIFT                                             (0u)
#define MTU_TWCRB_WRE                                                          (0x01u)
#define MTU_TWCRB_WRE_SHIFT                                                    (0u)
#define MTU_TWCRB_SCC                                                          (0x02u)
#define MTU_TWCRB_SCC_SHIFT                                                    (1u)
#define MTU_TWCRB_CCE                                                          (0x80u)
#define MTU_TWCRB_CCE_SHIFT                                                    (7u)
#define MTU_TMDR2B_DRS                                                         (0x01u)
#define MTU_TMDR2B_DRS_SHIFT                                                   (0u)
#define MTU_TSTRB_CST6                                                         (0x40u)
#define MTU_TSTRB_CST6_SHIFT                                                   (6u)
#define MTU_TSTRB_CST7                                                         (0x80u)
#define MTU_TSTRB_CST7_SHIFT                                                   (7u)
#define MTU_TSYRB_SYNC6                                                        (0x40u)
#define MTU_TSYRB_SYNC6_SHIFT                                                  (6u)
#define MTU_TSYRB_SYNC7                                                        (0x80u)
#define MTU_TSYRB_SYNC7_SHIFT                                                  (7u)
#define MTU_TRWERB_RWE                                                         (0x01u)
#define MTU_TRWERB_RWE_SHIFT                                                   (0u)

#endif
