/*******************************************************************************
* DISCLAIMER
* This software is supplied by Renesas Electronics Corporation and is only
* intended for use with Renesas products. No other uses are authorized. This
* software is owned by Renesas Electronics Corporation and is protected under
* all applicable laws, including copyright laws.
* THIS SOFTWARE IS PROVIDED "AS IS" AND RENESAS MAKES NO WARRANTIES REGARDING
* THIS SOFTWARE, WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING BUT NOT
* LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE
* AND NON-INFRINGEMENT. ALL SUCH WARRANTIES ARE EXPRESSLY DISCLAIMED.
* TO THE MAXIMUM EXTENT PERMITTED NOT PROHIBITED BY LAW, NEITHER RENESAS
* ELECTRONICS CORPORATION NOR ANY OF ITS AFFILIATED COMPANIES SHALL BE LIABLE
* FOR ANY DIRECT, INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES FOR
* ANY REASON RELATED TO THIS SOFTWARE, EVEN IF RENESAS OR ITS AFFILIATES HAVE
* BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
* Renesas reserves the right, without notice, to make changes to this software
* and to discontinue the availability of this software. By using this software,
* you agree to the additional terms and conditions found by accessing the
* following link:
* http://www.renesas.com/disclaimer
* Copyright (C) 2018 Renesas Electronics Corporation. All rights reserved.
*******************************************************************************/ 
#ifndef EPTPC1_IOBITMASK_H
#define EPTPC1_IOBITMASK_H


/* ==== Mask values for IO registers ==== */

#define EPTPC1_SYSR_OFMUD                                                      (0x00000001u)
#define EPTPC1_SYSR_OFMUD_SHIFT                                                (0u)
#define EPTPC1_SYSR_INTCHG                                                     (0x00000002u)
#define EPTPC1_SYSR_INTCHG_SHIFT                                               (1u)
#define EPTPC1_SYSR_MPDUD                                                      (0x00000004u)
#define EPTPC1_SYSR_MPDUD_SHIFT                                                (2u)
#define EPTPC1_SYSR_DRPTO                                                      (0x00000010u)
#define EPTPC1_SYSR_DRPTO_SHIFT                                                (4u)
#define EPTPC1_SYSR_INTDEV                                                     (0x00000020u)
#define EPTPC1_SYSR_INTDEV_SHIFT                                               (5u)
#define EPTPC1_SYSR_DRQOVR                                                     (0x00000040u)
#define EPTPC1_SYSR_DRQOVR_SHIFT                                               (6u)
#define EPTPC1_SYSR_RECLP                                                      (0x00001000u)
#define EPTPC1_SYSR_RECLP_SHIFT                                                (12u)
#define EPTPC1_SYSR_INFABT                                                     (0x00004000u)
#define EPTPC1_SYSR_INFABT_SHIFT                                               (14u)
#define EPTPC1_SYSR_RESDN                                                      (0x00010000u)
#define EPTPC1_SYSR_RESDN_SHIFT                                                (16u)
#define EPTPC1_SYSR_GENDN                                                      (0x00020000u)
#define EPTPC1_SYSR_GENDN_SHIFT                                                (17u)
#define EPTPC1_SYIPR_OFMUD                                                     (0x00000001u)
#define EPTPC1_SYIPR_OFMUD_SHIFT                                               (0u)
#define EPTPC1_SYIPR_INTCHG                                                    (0x00000002u)
#define EPTPC1_SYIPR_INTCHG_SHIFT                                              (1u)
#define EPTPC1_SYIPR_MPDUD                                                     (0x00000004u)
#define EPTPC1_SYIPR_MPDUD_SHIFT                                               (2u)
#define EPTPC1_SYIPR_DRPTO                                                     (0x00000010u)
#define EPTPC1_SYIPR_DRPTO_SHIFT                                               (4u)
#define EPTPC1_SYIPR_INTDEV                                                    (0x00000020u)
#define EPTPC1_SYIPR_INTDEV_SHIFT                                              (5u)
#define EPTPC1_SYIPR_DRQOVR                                                    (0x00000040u)
#define EPTPC1_SYIPR_DRQOVR_SHIFT                                              (6u)
#define EPTPC1_SYIPR_RECLP                                                     (0x00001000u)
#define EPTPC1_SYIPR_RECLP_SHIFT                                               (12u)
#define EPTPC1_SYIPR_INFABT                                                    (0x00004000u)
#define EPTPC1_SYIPR_INFABT_SHIFT                                              (14u)
#define EPTPC1_SYIPR_RESDN                                                     (0x00010000u)
#define EPTPC1_SYIPR_RESDN_SHIFT                                               (16u)
#define EPTPC1_SYIPR_GENDN                                                     (0x00020000u)
#define EPTPC1_SYIPR_GENDN_SHIFT                                               (17u)
#define EPTPC1_SYMACRU_SYMACRU                                                 (0x00FFFFFFu)
#define EPTPC1_SYMACRU_SYMACRU_SHIFT                                           (0u)
#define EPTPC1_SYMACRL_SYMACRL                                                 (0x00FFFFFFu)
#define EPTPC1_SYMACRL_SYMACRL_SHIFT                                           (0u)
#define EPTPC1_SYLLCCTLR_CTL                                                   (0x000000FFu)
#define EPTPC1_SYLLCCTLR_CTL_SHIFT                                             (0u)
#define EPTPC1_SYIPADDRR_SYIPADDRR                                             (0xFFFFFFFFu)
#define EPTPC1_SYIPADDRR_SYIPADDRR_SHIFT                                       (0u)
#define EPTPC1_SYSPVRR_VER                                                     (0x0000000Fu)
#define EPTPC1_SYSPVRR_VER_SHIFT                                               (0u)
#define EPTPC1_SYSPVRR_TRSP                                                    (0x000000F0u)
#define EPTPC1_SYSPVRR_TRSP_SHIFT                                              (4u)
#define EPTPC1_SYDOMR_DNUM                                                     (0x000000FFu)
#define EPTPC1_SYDOMR_DNUM_SHIFT                                               (0u)
#define EPTPC1_ANFR_FLAG0                                                      (0x00000001u)
#define EPTPC1_ANFR_FLAG0_SHIFT                                                (0u)
#define EPTPC1_ANFR_FLAG1                                                      (0x00000002u)
#define EPTPC1_ANFR_FLAG1_SHIFT                                                (1u)
#define EPTPC1_ANFR_FLAG2                                                      (0x00000004u)
#define EPTPC1_ANFR_FLAG2_SHIFT                                                (2u)
#define EPTPC1_ANFR_FLAG3                                                      (0x00000008u)
#define EPTPC1_ANFR_FLAG3_SHIFT                                                (3u)
#define EPTPC1_ANFR_FLAG4                                                      (0x00000010u)
#define EPTPC1_ANFR_FLAG4_SHIFT                                                (4u)
#define EPTPC1_ANFR_FLAG5                                                      (0x00000020u)
#define EPTPC1_ANFR_FLAG5_SHIFT                                                (5u)
#define EPTPC1_ANFR_FLAG8                                                      (0x00000100u)
#define EPTPC1_ANFR_FLAG8_SHIFT                                                (8u)
#define EPTPC1_ANFR_FLAG10                                                     (0x00000400u)
#define EPTPC1_ANFR_FLAG10_SHIFT                                               (10u)
#define EPTPC1_ANFR_FLAG13                                                     (0x00002000u)
#define EPTPC1_ANFR_FLAG13_SHIFT                                               (13u)
#define EPTPC1_ANFR_FLAG14                                                     (0x00004000u)
#define EPTPC1_ANFR_FLAG14_SHIFT                                               (14u)
#define EPTPC1_SYNFR_FLAG10                                                    (0x00000400u)
#define EPTPC1_SYNFR_FLAG10_SHIFT                                              (10u)
#define EPTPC1_SYNFR_FLAG13                                                    (0x00002000u)
#define EPTPC1_SYNFR_FLAG13_SHIFT                                              (13u)
#define EPTPC1_SYNFR_FLAG14                                                    (0x00004000u)
#define EPTPC1_SYNFR_FLAG14_SHIFT                                              (14u)
#define EPTPC1_DYRQFR_FLAG10                                                   (0x00000400u)
#define EPTPC1_DYRQFR_FLAG10_SHIFT                                             (10u)
#define EPTPC1_DYRQFR_FLAG13                                                   (0x00002000u)
#define EPTPC1_DYRQFR_FLAG13_SHIFT                                             (13u)
#define EPTPC1_DYRQFR_FLAG14                                                   (0x00004000u)
#define EPTPC1_DYRQFR_FLAG14_SHIFT                                             (14u)
#define EPTPC1_DYRPFR_FLAG8                                                    (0x00000100u)
#define EPTPC1_DYRPFR_FLAG8_SHIFT                                              (8u)
#define EPTPC1_DYRPFR_FLAG9                                                    (0x00000200u)
#define EPTPC1_DYRPFR_FLAG9_SHIFT                                              (9u)
#define EPTPC1_DYRPFR_FLAG10                                                   (0x00000400u)
#define EPTPC1_DYRPFR_FLAG10_SHIFT                                             (10u)
#define EPTPC1_DYRPFR_FLAG13                                                   (0x00002000u)
#define EPTPC1_DYRPFR_FLAG13_SHIFT                                             (13u)
#define EPTPC1_DYRPFR_FLAG14                                                   (0x00004000u)
#define EPTPC1_DYRPFR_FLAG14_SHIFT                                             (14u)
#define EPTPC1_SYCIDRL_SYCIDRL                                                 (0xFFFFFFFFu)
#define EPTPC1_SYCIDRL_SYCIDRL_SHIFT                                           (0u)
#define EPTPC1_SYCIDRU_SYCIDRU                                                 (0xFFFFFFFFu)
#define EPTPC1_SYCIDRU_SYCIDRU_SHIFT                                           (0u)
#define EPTPC1_SYPNUMR_PNUM                                                    (0x0000FFFFu)
#define EPTPC1_SYPNUMR_PNUM_SHIFT                                              (0u)
#define EPTPC1_SYRVLDR_BMUP                                                    (0x00000001u)
#define EPTPC1_SYRVLDR_BMUP_SHIFT                                              (0u)
#define EPTPC1_SYRVLDR_STUP                                                    (0x00000002u)
#define EPTPC1_SYRVLDR_STUP_SHIFT                                              (1u)
#define EPTPC1_SYRVLDR_ANUP                                                    (0x00000004u)
#define EPTPC1_SYRVLDR_ANUP_SHIFT                                              (2u)
#define EPTPC1_SYRFL1R_ANCE                                                    (0x00000003u)
#define EPTPC1_SYRFL1R_ANCE_SHIFT                                              (0u)
#define EPTPC1_SYRFL1R_SYNC                                                    (0x00000070u)
#define EPTPC1_SYRFL1R_SYNC_SHIFT                                              (4u)
#define EPTPC1_SYRFL1R_FUP                                                     (0x00000700u)
#define EPTPC1_SYRFL1R_FUP_SHIFT                                               (8u)
#define EPTPC1_SYRFL1R_DRQ                                                     (0x00007000u)
#define EPTPC1_SYRFL1R_DRQ_SHIFT                                               (12u)
#define EPTPC1_SYRFL1R_DRP                                                     (0x00070000u)
#define EPTPC1_SYRFL1R_DRP_SHIFT                                               (16u)
#define EPTPC1_SYRFL1R_PDRQ                                                    (0x00700000u)
#define EPTPC1_SYRFL1R_PDRQ_SHIFT                                              (20u)
#define EPTPC1_SYRFL1R_PDRP                                                    (0x07000000u)
#define EPTPC1_SYRFL1R_PDRP_SHIFT                                              (24u)
#define EPTPC1_SYRFL1R_PDFUP                                                   (0x70000000u)
#define EPTPC1_SYRFL1R_PDFUP_SHIFT                                             (28u)
#define EPTPC1_SYRFL2R_MAN                                                     (0x00000003u)
#define EPTPC1_SYRFL2R_MAN_SHIFT                                               (0u)
#define EPTPC1_SYRFL2R_SIG                                                     (0x00000030u)
#define EPTPC1_SYRFL2R_SIG_SHIFT                                               (4u)
#define EPTPC1_SYRFL2R_ILL                                                     (0x30000000u)
#define EPTPC1_SYRFL2R_ILL_SHIFT                                               (28u)
#define EPTPC1_SYTRENR_ANCE                                                    (0x00000001u)
#define EPTPC1_SYTRENR_ANCE_SHIFT                                              (0u)
#define EPTPC1_SYTRENR_SYNC                                                    (0x00000010u)
#define EPTPC1_SYTRENR_SYNC_SHIFT                                              (4u)
#define EPTPC1_SYTRENR_DRQ                                                     (0x00000100u)
#define EPTPC1_SYTRENR_DRQ_SHIFT                                               (8u)
#define EPTPC1_SYTRENR_PDRQ                                                    (0x00001000u)
#define EPTPC1_SYTRENR_PDRQ_SHIFT                                              (12u)
#define EPTPC1_MTCIDL_MTCIDL                                                   (0xFFFFFFFFu)
#define EPTPC1_MTCIDL_MTCIDL_SHIFT                                             (0u)
#define EPTPC1_MTCIDU_MTCIDU                                                   (0xFFFFFFFFu)
#define EPTPC1_MTCIDU_MTCIDU_SHIFT                                             (0u)
#define EPTPC1_MTPID_PNUM                                                      (0x0000FFFFu)
#define EPTPC1_MTPID_PNUM_SHIFT                                                (0u)
#define EPTPC1_SYTLIR_ANCE                                                     (0x000000FFu)
#define EPTPC1_SYTLIR_ANCE_SHIFT                                               (0u)
#define EPTPC1_SYTLIR_SYNC                                                     (0x0000FF00u)
#define EPTPC1_SYTLIR_SYNC_SHIFT                                               (8u)
#define EPTPC1_SYTLIR_DREQ                                                     (0x00FF0000u)
#define EPTPC1_SYTLIR_DREQ_SHIFT                                               (16u)
#define EPTPC1_SYRLIR_ANCE                                                     (0x000000FFu)
#define EPTPC1_SYRLIR_ANCE_SHIFT                                               (0u)
#define EPTPC1_SYRLIR_SYNC                                                     (0x0000FF00u)
#define EPTPC1_SYRLIR_SYNC_SHIFT                                               (8u)
#define EPTPC1_SYRLIR_DRESP                                                    (0x00FF0000u)
#define EPTPC1_SYRLIR_DRESP_SHIFT                                              (16u)
#define EPTPC1_OFMRL_OFMRL                                                     (0xFFFFFFFFu)
#define EPTPC1_OFMRL_OFMRL_SHIFT                                               (0u)
#define EPTPC1_OFMRU_OFMRU                                                     (0xFFFFFFFFu)
#define EPTPC1_OFMRU_OFMRU_SHIFT                                               (0u)
#define EPTPC1_MPDRU_MPDRU                                                     (0xFFFFFFFFu)
#define EPTPC1_MPDRU_MPDRU_SHIFT                                               (0u)
#define EPTPC1_MPDRL_MPDRL                                                     (0xFFFFFFFFu)
#define EPTPC1_MPDRL_MPDRL_SHIFT                                               (0u)
#define EPTPC1_GMPR_GMPR2                                                      (0x000000FFu)
#define EPTPC1_GMPR_GMPR2_SHIFT                                                (0u)
#define EPTPC1_GMPR_GMPR1                                                      (0x00FF0000u)
#define EPTPC1_GMPR_GMPR1_SHIFT                                                (16u)
#define EPTPC1_GMCQR_GMCQR                                                     (0xFFFFFFFFu)
#define EPTPC1_GMCQR_GMCQR_SHIFT                                               (0u)
#define EPTPC1_GMIDRU_GMIDRU                                                   (0xFFFFFFFFu)
#define EPTPC1_GMIDRU_GMIDRU_SHIFT                                             (0u)
#define EPTPC1_GMIDRL_GMIDRL                                                   (0xFFFFFFFFu)
#define EPTPC1_GMIDRL_GMIDRL_SHIFT                                             (0u)
#define EPTPC1_CUOTSR_TSRC                                                     (0x000000FFu)
#define EPTPC1_CUOTSR_TSRC_SHIFT                                               (0u)
#define EPTPC1_CUOTSR_CUTO                                                     (0xFFFF0000u)
#define EPTPC1_CUOTSR_CUTO_SHIFT                                               (16u)
#define EPTPC1_SRR_SRMV                                                        (0x0000FFFFu)
#define EPTPC1_SRR_SRMV_SHIFT                                                  (0u)
#define EPTPC1_PPMACRU_PPMACRU                                                 (0x00FFFFFFu)
#define EPTPC1_PPMACRU_PPMACRU_SHIFT                                           (0u)
#define EPTPC1_PPMACRL_PPMACRL                                                 (0x00FFFFFFu)
#define EPTPC1_PPMACRL_PPMACRL_SHIFT                                           (0u)
#define EPTPC1_PDMACRU_PDMACRU                                                 (0x00FFFFFFu)
#define EPTPC1_PDMACRU_PDMACRU_SHIFT                                           (0u)
#define EPTPC1_PDMACRL_PDMACRL                                                 (0x00FFFFFFu)
#define EPTPC1_PDMACRL_PDMACRL_SHIFT                                           (0u)
#define EPTPC1_PETYPER_TYPE                                                    (0x0000FFFFu)
#define EPTPC1_PETYPER_TYPE_SHIFT                                              (0u)
#define EPTPC1_PPIPR_PPIPR                                                     (0xFFFFFFFFu)
#define EPTPC1_PPIPR_PPIPR_SHIFT                                               (0u)
#define EPTPC1_PDIPR_PDIPR                                                     (0xFFFFFFFFu)
#define EPTPC1_PDIPR_PDIPR_SHIFT                                               (0u)
#define EPTPC1_PETOSR_EVTO                                                     (0x000000FFu)
#define EPTPC1_PETOSR_EVTO_SHIFT                                               (0u)
#define EPTPC1_PGTOSR_GETO                                                     (0x000000FFu)
#define EPTPC1_PGTOSR_GETO_SHIFT                                               (0u)
#define EPTPC1_PPTTLR_PRTL                                                     (0x000000FFu)
#define EPTPC1_PPTTLR_PRTL_SHIFT                                               (0u)
#define EPTPC1_PDTTLR_PDTL                                                     (0x000000FFu)
#define EPTPC1_PDTTLR_PDTL_SHIFT                                               (0u)
#define EPTPC1_PEUDPR_EVUPT                                                    (0x0000FFFFu)
#define EPTPC1_PEUDPR_EVUPT_SHIFT                                              (0u)
#define EPTPC1_PGUDPR_GEUPT                                                    (0x0000FFFFu)
#define EPTPC1_PGUDPR_GEUPT_SHIFT                                              (0u)
#define EPTPC1_FFLTR_SEL                                                       (0x00000001u)
#define EPTPC1_FFLTR_SEL_SHIFT                                                 (0u)
#define EPTPC1_FFLTR_PRT                                                       (0x00000002u)
#define EPTPC1_FFLTR_PRT_SHIFT                                                 (1u)
#define EPTPC1_FFLTR_ENB                                                       (0x00000004u)
#define EPTPC1_FFLTR_ENB_SHIFT                                                 (2u)
#define EPTPC1_FFLTR_EXTPRM                                                    (0x00010000u)
#define EPTPC1_FFLTR_EXTPRM_SHIFT                                              (16u)
#define EPTPC1_FMAC0RU_FMAC0RU                                                 (0x00FFFFFFu)
#define EPTPC1_FMAC0RU_FMAC0RU_SHIFT                                           (0u)
#define EPTPC1_FMAC0RL_FMAC0RL                                                 (0x00FFFFFFu)
#define EPTPC1_FMAC0RL_FMAC0RL_SHIFT                                           (0u)
#define EPTPC1_FMAC1RU_FMAC1RU                                                 (0x00FFFFFFu)
#define EPTPC1_FMAC1RU_FMAC1RU_SHIFT                                           (0u)
#define EPTPC1_FMAC1RL_FMAC1RL                                                 (0x00FFFFFFu)
#define EPTPC1_FMAC1RL_FMAC1RL_SHIFT                                           (0u)
#define EPTPC1_DASYMRU_DASYMRU                                                 (0x0000FFFFu)
#define EPTPC1_DASYMRU_DASYMRU_SHIFT                                           (0u)
#define EPTPC1_DASYMRL_DASYMRL                                                 (0xFFFFFFFFu)
#define EPTPC1_DASYMRL_DASYMRL_SHIFT                                           (0u)
#define EPTPC1_TSLATR_EGP                                                      (0x0000FFFFu)
#define EPTPC1_TSLATR_EGP_SHIFT                                                (0u)
#define EPTPC1_TSLATR_INGP                                                     (0xFFFF0000u)
#define EPTPC1_TSLATR_INGP_SHIFT                                               (16u)
#define EPTPC1_SYCONFR_TCYC                                                    (0x000000FFu)
#define EPTPC1_SYCONFR_TCYC_SHIFT                                              (0u)
#define EPTPC1_SYCONFR_SBDIS                                                   (0x00001000u)
#define EPTPC1_SYCONFR_SBDIS_SHIFT                                             (12u)
#define EPTPC1_SYCONFR_FILDIS                                                  (0x00010000u)
#define EPTPC1_SYCONFR_FILDIS_SHIFT                                            (16u)
#define EPTPC1_SYCONFR_TCMOD                                                   (0x00100000u)
#define EPTPC1_SYCONFR_TCMOD_SHIFT                                             (20u)
#define EPTPC1_SYFORMR_FORM0                                                   (0x00000001u)
#define EPTPC1_SYFORMR_FORM0_SHIFT                                             (0u)
#define EPTPC1_SYFORMR_FORM1                                                   (0x00000002u)
#define EPTPC1_SYFORMR_FORM1_SHIFT                                             (1u)
#define EPTPC1_RSTOUTR_RSTOUTR                                                 (0xFFFFFFFFu)
#define EPTPC1_RSTOUTR_RSTOUTR_SHIFT                                           (0u)

#endif
